- hosts: 127.0.0.1
  connection: local

  tasks:

#    - name: Install fx json viewer
#      snap:
#        name: fx
#      become: yes

    - name: Copy file with env variables
      ansible.builtin.copy:
        src: dot-files/.myenv
        dest: ~/.myenv

    - name: Copy gitconfig
      ansible.builtin.copy:
        src: dot-files/.gitconfig
        dest: ~/.gitconfig

    - name: Ensure env variables load in profile
      ansible.builtin.blockinfile:
        path: ~/.profile
        block: |
          # Source file with custom environment values
          . "$HOME/.myenv"
